export interface IComplaintFinder {
    complaintGroupCode: string,
    complaintGroupDesc?: string,
    models?: Array<string>,
    from?: string,
    to?: string,
    mis?: number
}

export interface IComplaint {
    _id: string,
    Dealer_Code: string,
    Dealer_Code_Description: string,
    Dealer_City: string,
    PCR_Number: string,
    VC_Number: string,
    VC_Description: string,
    Model: string,
    Sub_Model: string,
    Chassis_No: string,
    Chassis_Type: string,
    Production_Month: string,
    Kilometers_Covered: string,
    Complaint_Group: string,
    Complaint_Group_Description: string,
    Complaint_Code: string,
    Complaint_Code_Description: string,
    Sale_Month: string,
    Complaint_Month: string,
    Complaint_Reported_Date: string,
    Diff_between_Complaint_Sales_Month: string,
    Claim_Category: string,
    Claim_Category_Description: string,
    Claims_Indicator: string,
    No_of_Complaints: string,
    Part_Number: string,
    Part_Description: string,
    Part_Quantity: string,
    Part_Rate: string,
    Actual_Labour_Charge: string,
    Miscellaneous_Charge: string,
    Special_Labour_Charges: string,
    Total_Expenses: string,
    Customer_Complaint: string,
    Investigation: string,
    Action_Taken: string
}